package(default_visibility = ["//visibility:public"])

exports_files([
    "go.mod",
    "go.sum",
])

test_suite(
    name = "test",
    tests = [
        "//examples:test",
        "//tests:browser_test",
        "//tests:validation_test",
    ],
)

filegroup(
    name = "artifacts",
    testonly = True,
    srcs = [
        "//examples:artifacts",
        "//playwright:extensions",
        "@browser_payload//:chromium",
    ],
)
