load("@io_bazel_rules_go//go:def.bzl", "go_test")
load(":inventory.bzl", "browser_inventory")
load(":validation_tests.bzl", "validation_test")

package(
    default_testonly = True,
    default_visibility = ["//:__pkg__"],
)

validation_test(name = "validation_test")

browser_inventory(
    name = "browser_inventory",
    browser = "@browser_payload//:chromium",
)

go_test(
    name = "browser_test",
    srcs = ["browser_test.go"],
    data = [
        ":browser_inventory",
        "//examples/browser:index.html",
        "@browser_payload//:chromium",
    ],
    env = {
        "BROWSER_PAGE": "$(rlocationpath //examples/browser:index.html)",
        "BROWSER_INVENTORY": "$(rlocationpath :browser_inventory)",
    },
    tags = ["no-sandbox"],
    deps = [
        "@io_bazel_rules_go//go/runfiles",
        "@latticebuild_graceproc//:graceproc",
    ],
)
