package(
    default_testonly = True,
    default_visibility = ["//visibility:public"],
)

filegroup(
    name = "artifacts",
    srcs = [
        "//examples/browser:chromium",
        "//examples/browser:index.html",
    ],
)

test_suite(
    name = "test",
    tests = [
        "//tests:browser_test",
        "//tests:validation_test",
    ],
)
